Цель: Преобразовать признаки и разбить датасет на обучающую и тестовую выборку.

Для начала как всегда добавляем библиотеки и считываем данные с файла.

In [2]:
import pandas as pd
import numpy as np

In [3]:
#считывание данных с файла
df = pd.read_csv('vgsales_19.csv')
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,7164,Discovery Kids: Dolphin Discovery,DS,2008.0,Simulation,505 Games,0.21,0.00,0.00,0.01,0.22
1,15834,LifeSigns: Surgical Unit,DS,2005.0,Simulation,JoWood Productions,0.01,0.01,0.00,0.00,0.02
2,11539,Sengoku Musou 3: Moushouden,Wii,2011.0,Action,Ackkstudios,0.00,0.00,0.08,0.00,0.08
3,593,LittleBigPlanet,PSP,2009.0,Platform,Sony Computer Entertainment,0.64,1.24,0.01,0.69,2.58
4,12211,Yoake Yori Ruriiro na: Brighter than Dawning Blue,PS2,2006.0,Adventure,Aria,0.00,0.00,0.07,0.00,0.07
...,...,...,...,...,...,...,...,...,...,...,...
548,4537,Castlevania: Portrait of Ruin,DS,2006.0,Platform,Konami Digital Entertainment,0.33,0.03,0.04,0.03,0.43
549,11524,Puzzler Mind Gym 3D,3DS,2011.0,Puzzle,Ubisoft,0.07,0.00,0.00,0.00,0.08
550,1366,Inazuma Eleven 2,DS,2009.0,Role-Playing,Nintendo,0.00,0.21,1.18,0.03,1.42
551,4135,Tomb Raider: Underworld,Wii,2008.0,Action,Eidos Interactive,0.14,0.28,0.00,0.06,0.48
552,3828,GT Pro Series,Wii,2006.0,Racing,Ubisoft,0.46,0.01,0.02,0.04,0.52

Продемонстрировать работу OrdinalEncoder и использовать его на датасете:
Подключаем специально для этого библиотеку с расширением OrdinalEncoder. Далее записывем в первую переменную координату. Указываем двумерный массив с указанием столбцов данных. Функция fit вычисляет формулировку для преобразования столбцов на основе стандартного масштабирования.

In [4]:
from sklearn.preprocessing import OrdinalEncoder

Oenc = OrdinalEncoder()
Oenc.fit(df[['Platform','Publisher']])
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,7164,Discovery Kids: Dolphin Discovery,DS,2008.0,Simulation,505 Games,0.21,0.00,0.00,0.01,0.22
1,15834,LifeSigns: Surgical Unit,DS,2005.0,Simulation,JoWood Productions,0.01,0.01,0.00,0.00,0.02
2,11539,Sengoku Musou 3: Moushouden,Wii,2011.0,Action,Ackkstudios,0.00,0.00,0.08,0.00,0.08
3,593,LittleBigPlanet,PSP,2009.0,Platform,Sony Computer Entertainment,0.64,1.24,0.01,0.69,2.58
4,12211,Yoake Yori Ruriiro na: Brighter than Dawning Blue,PS2,2006.0,Adventure,Aria,0.00,0.00,0.07,0.00,0.07
...,...,...,...,...,...,...,...,...,...,...,...
548,4537,Castlevania: Portrait of Ruin,DS,2006.0,Platform,Konami Digital Entertainment,0.33,0.03,0.04,0.03,0.43
549,11524,Puzzler Mind Gym 3D,3DS,2011.0,Puzzle,Ubisoft,0.07,0.00,0.00,0.00,0.08
550,1366,Inazuma Eleven 2,DS,2009.0,Role-Playing,Nintendo,0.00,0.21,1.18,0.03,1.42
551,4135,Tomb Raider: Underworld,Wii,2008.0,Action,Eidos Interactive,0.14,0.28,0.00,0.06,0.48
552,3828,GT Pro Series,Wii,2006.0,Racing,Ubisoft,0.46,0.01,0.02,0.04,0.52

Вызовем функцию "categories" для определения значений в записанной переменной. Например, в первой строке столбца Platform  стоит слово - DS, по списку оно под 3 номером. Произведем кодирование.

In [5]:
Oenc.categories_

[array(['2600', '3DS', 'DC', 'DS', 'GB', 'GBA', 'GC', 'GEN', 'N64', 'NES',
        'PC', 'PS', 'PS2', 'PS3', 'PS4', 'PSP', 'PSV', 'SAT', 'SNES', 'WS',
        'Wii', 'WiiU', 'X360', 'XB', 'XOne'], dtype=object),
 array(['3DO', '505 Games', '5pb', 'AQ Interactive',
        'Acclaim Entertainment', 'Ackkstudios', 'Activision',
        'Activision Value', 'Alchemist', 'Aqua Plus', 'Arc System Works',
        'Arena Entertainment', 'Aria', 'ArtDink', 'Aspyr', 'Astragon',
        'Atari', 'Atlus', 'Avanquest Software', 'BAM! Entertainment',
        'Banpresto', 'Bethesda Softworks', 'Big Fish Games',
        'Blast! Entertainment Ltd', 'CTO SpA', 'Capcom', 'Cave',
        'ChunSoft', 'Codemasters', 'Crave Entertainment', 'Crimson Cow',
        'D3Publisher', 'DHM Interactive', 'DTP Entertainment',
        'Deep Silver', 'Devolver Digital', 'Disney Interactive Studios',
        'Eidos Interactive', 'Electronic Arts', 'Encore', 'Enterbrain',
        'Evolved Games', 'Falcom Corporation', 'Focus Home Interactive',
        'Foreign Media Games', 'FuRyu', 'Funbox Media', 'Funsta', 'GSP',
        'GT Interactive', 'Gaga', 'Game Factory', 'GameMill Entertainment',
        'Genki', 'Global Star', 'Graffiti', 'Gremlin Interactive Ltd',
        'Hackberry', 'Harmonix Music Systems', 'Hasbro Interactive',
        'Hip Interactive', 'Hudson Soft', 'Idea Factory',
        'Idea Factory International', 'Ignition Entertainment', 'Imagic',
        'Infogrames', 'Interplay', 'Irem Software Engineering',
        'JoWood Productions', 'Kadokawa Games', 'Kadokawa Shoten',
        'Kalypso Media', 'Knowledge Adventure',
        'Konami Digital Entertainment', 'LucasArts', 'MTV Games', 'Magix',
        'Majesco Entertainment', 'Marvelous Entertainment',
        'Marvelous Interactive', 'Mattel Interactive', 'Media Works',
        'Microids', 'Microsoft Game Studios', 'Midway Games',
        'Milestone S.r.l.', 'Mindscape', 'Misawa', 'Mojang',
        'Myelin Media', 'NEC', 'NEC Interchannel', 'Namco Bandai Games',
        'NewKidCo', 'Nintendo', 'Nippon Ichi Software', 'Nordic Games',
        'O-Games', 'Oxygen Interactive', 'P2 Games', 'PQube', 'Phenomedia',
        'PlayV', 'PopCap Games', 'Red Storm Entertainment',
        'Reef Entertainment', 'Rising Star Games', 'Riverhillsoft',
        'Rondomedia', 'SCi', 'SSI', 'Sammy Corporation', 'Sega',
        'Shogakukan', 'Sony Computer Entertainment', 'SouthPeak Games',
        'Spike', 'Square', 'Square Enix', 'SquareSoft', 'Storm City Games',
        'System 3', 'TDK Mediactive', 'THQ', 'Taito', 'Takara',
        'Take-Two Interactive', 'Tecmo Koei', 'Telegames',
        'Telltale Games', 'U.S. Gold', 'Ubisoft', 'Ubisoft Annecy',
        'Universal Interactive', 'Unknown', 'Vir2L Studios',
        'Virgin Interactive', 'Vivendi Games',
        'Warner Bros. Interactive Entertainment', 'Xplosiv',
        'Zoo Digital Publishing', 'bitComposer Games', nan], dtype=object)]

Обратимся к столбцам датасета и через функцию fit_transform, заменим словосочетания на цифры. Исходя из этого результата можно понять, что все правильно и DS находится под 3 номером, но тк счет идет с 0, переменная записалась под 2.

In [6]:
Oenc = OrdinalEncoder()
df[['Platform','Publisher']] = Oenc.fit_transform(df[['Platform','Publisher']])
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,7164,Discovery Kids: Dolphin Discovery,3.0,2008.0,Simulation,1.0,0.21,0.00,0.00,0.01,0.22
1,15834,LifeSigns: Surgical Unit,3.0,2005.0,Simulation,69.0,0.01,0.01,0.00,0.00,0.02
2,11539,Sengoku Musou 3: Moushouden,20.0,2011.0,Action,5.0,0.00,0.00,0.08,0.00,0.08
3,593,LittleBigPlanet,15.0,2009.0,Platform,115.0,0.64,1.24,0.01,0.69,2.58
4,12211,Yoake Yori Ruriiro na: Brighter than Dawning Blue,12.0,2006.0,Adventure,12.0,0.00,0.00,0.07,0.00,0.07
...,...,...,...,...,...,...,...,...,...,...,...
548,4537,Castlevania: Portrait of Ruin,3.0,2006.0,Platform,74.0,0.33,0.03,0.04,0.03,0.43
549,11524,Puzzler Mind Gym 3D,1.0,2011.0,Puzzle,132.0,0.07,0.00,0.00,0.00,0.08
550,1366,Inazuma Eleven 2,3.0,2009.0,Role-Playing,95.0,0.00,0.21,1.18,0.03,1.42
551,4135,Tomb Raider: Underworld,20.0,2008.0,Action,37.0,0.14,0.28,0.00,0.06,0.48
552,3828,GT Pro Series,20.0,2006.0,Racing,132.0,0.46,0.01,0.02,0.04,0.52

Обязательно преобразовать 1 категориальный признак с помощью LabelEncoder.
Подключаем библиотку LabelEncoder. Данное кодирование одинаково с предыдущем, но различие все же есть. Различие в том, что данное кодирование преобразует целевую переменную.

In [7]:
from sklearn.preprocessing import LabelEncoder
Lenc = LabelEncoder()
Lenc.fit(df['Genre'])
df['Genre'] = Lenc.fit_transform(df['Genre'])
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,7164,Discovery Kids: Dolphin Discovery,3.0,2008.0,9,1.0,0.21,0.00,0.00,0.01,0.22
1,15834,LifeSigns: Surgical Unit,3.0,2005.0,9,69.0,0.01,0.01,0.00,0.00,0.02
2,11539,Sengoku Musou 3: Moushouden,20.0,2011.0,0,5.0,0.00,0.00,0.08,0.00,0.08
3,593,LittleBigPlanet,15.0,2009.0,4,115.0,0.64,1.24,0.01,0.69,2.58
4,12211,Yoake Yori Ruriiro na: Brighter than Dawning Blue,12.0,2006.0,1,12.0,0.00,0.00,0.07,0.00,0.07
...,...,...,...,...,...,...,...,...,...,...,...
548,4537,Castlevania: Portrait of Ruin,3.0,2006.0,4,74.0,0.33,0.03,0.04,0.03,0.43
549,11524,Puzzler Mind Gym 3D,1.0,2011.0,5,132.0,0.07,0.00,0.00,0.00,0.08
550,1366,Inazuma Eleven 2,3.0,2009.0,7,95.0,0.00,0.21,1.18,0.03,1.42
551,4135,Tomb Raider: Underworld,20.0,2008.0,0,37.0,0.14,0.28,0.00,0.06,0.48
552,3828,GT Pro Series,20.0,2006.0,6,132.0,0.46,0.01,0.02,0.04,0.52

Видно как закодировались переменные.

In [8]:
Lenc.classes_

array(['Action', 'Adventure', 'Fighting', 'Misc', 'Platform', 'Puzzle',
       'Racing', 'Role-Playing', 'Shooter', 'Simulation', 'Sports',
       'Strategy'], dtype=object)

Провести нормализацию с помощью Normalize на числовых признаках.
Подключаем библиотеку Normalizer.
Принцип нормализации работает так - он вычитает минимальное значение из каждой записи, затем делит результат на разница между максимальным значением и минимальным значением. 
Передадим в переменную столбцы, которые будут нормализированы.

In [9]:
from sklearn.preprocessing import Normalizer

Norm = Normalizer()

df[['NA_Sales', 'EU_Sales']] = Norm.fit_transform(df[['NA_Sales', 'EU_Sales']])
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,7164,Discovery Kids: Dolphin Discovery,3.0,2008.0,9,1.0,1.000000,0.000000,0.00,0.01,0.22
1,15834,LifeSigns: Surgical Unit,3.0,2005.0,9,69.0,0.707107,0.707107,0.00,0.00,0.02
2,11539,Sengoku Musou 3: Moushouden,20.0,2011.0,0,5.0,0.000000,0.000000,0.08,0.00,0.08
3,593,LittleBigPlanet,15.0,2009.0,4,115.0,0.458643,0.888621,0.01,0.69,2.58
4,12211,Yoake Yori Ruriiro na: Brighter than Dawning Blue,12.0,2006.0,1,12.0,0.000000,0.000000,0.07,0.00,0.07
...,...,...,...,...,...,...,...,...,...,...,...
548,4537,Castlevania: Portrait of Ruin,3.0,2006.0,4,74.0,0.995893,0.090536,0.04,0.03,0.43
549,11524,Puzzler Mind Gym 3D,1.0,2011.0,5,132.0,1.000000,0.000000,0.00,0.00,0.08
550,1366,Inazuma Eleven 2,3.0,2009.0,7,95.0,0.000000,1.000000,1.18,0.03,1.42
551,4135,Tomb Raider: Underworld,20.0,2008.0,0,37.0,0.447214,0.894427,0.00,0.06,0.48
552,3828,GT Pro Series,20.0,2006.0,6,132.0,0.999764,0.021734,0.02,0.04,0.52

Разделить датасет на обучающую и тестовую выборку.
Подключаем библиотеку train_test_split.
Y - столбец с обучающими данными, Х - столбец с тестовыми данными. Далле с помощью функции train_test_split разбиваем на выборки. 
random_state - параметр для управления перетасовкой,
test_size - значение с плавающей точкой. 
Посмотрим что находится в каждой переменной.

In [10]:
from sklearn.model_selection import train_test_split

Y = df['Year']
X = df.drop(columns=['Global_Sales'])

x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=42)

In [11]:
x_train

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales
18,4889,Dungeon Siege III,13.0,2011.0,7,119.0,0.771930,0.635707,0.03,0.06
325,13561,428: Fuusa Sareta Shibuya de,15.0,2009.0,1,117.0,0.000000,0.000000,0.04,0.00
486,3877,Jampack Winter 2002,12.0,2002.0,3,115.0,0.780869,0.624695,0.00,0.07
296,12660,Warriors: Legends of Troy,22.0,2011.0,0,128.0,0.000000,1.000000,0.01,0.01
478,12706,Blade Dancer: Lineage of Light,15.0,2006.0,7,16.0,1.000000,0.000000,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...
71,10727,The Land Before Time: Great Valley Racing Adve...,11.0,2001.0,6,123.0,0.780869,0.624695,0.00,0.01
106,4516,MLB 2002,11.0,2001.0,10,115.0,0.832050,0.554700,0.00,0.03
270,1216,Disney Fairies: Tinker Bell,3.0,2008.0,1,36.0,0.855732,0.517419,0.01,0.15
435,1403,Paper Mario,8.0,2000.0,7,95.0,0.955064,0.296399,0.59,0.02
102,10747,Rapala Pro Bass Fishing 2010,3.0,2010.0,10,6.0,1.000000,0.000000,0.00,0.01

In [12]:
x_test

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales
548,4537,Castlevania: Portrait of Ruin,3.0,2006.0,4,74.0,0.995893,0.090536,0.04,0.03
82,273,Gran Turismo 5 Prologue,13.0,2007.0,6,115.0,0.573162,0.819442,0.57,0.53
523,3439,Mega Man X7,12.0,2003.0,0,25.0,0.791285,0.611448,0.14,0.06
332,15686,Machi: Unmei no Kousaten,15.0,2006.0,1,27.0,0.000000,0.000000,0.02,0.00
132,14349,Hiiro no Kakera 2: Hisui no Shizuku,12.0,2007.0,1,62.0,0.000000,0.000000,0.03,0.00
...,...,...,...,...,...,...,...,...,...,...
140,12669,Tom Clancy's Ghost Recon: Advanced Warfighter,12.0,2006.0,8,132.0,0.832050,0.554700,0.00,0.01
149,4849,Mother 3,5.0,2006.0,7,95.0,0.000000,0.000000,0.39,0.01
498,1179,Hannah Montana: Music Jam,3.0,2007.0,0,36.0,0.944136,0.329557,0.00,0.15
153,7389,Senran Kagura 2: Deep Crimson,1.0,2014.0,0,79.0,0.948683,0.316228,0.08,0.01
172,16586,Carmageddon 64,8.0,1999.0,0,137.0,1.000000,0.000000,0.00,0.00

In [13]:
y_train

18     2011.0
325    2009.0
486    2002.0
296    2011.0
478    2006.0
        ...
71     2001.0
106    2001.0
270    2008.0
435    2000.0
102    2010.0
Name: Year, Length: 442, dtype: float64

In [14]:
y_test

548    2006.0
82     2007.0
523    2003.0
332    2006.0
132    2007.0
        ...
140    2006.0
149    2006.0
498    2007.0
153    2014.0
172    1999.0
Name: Year, Length: 111, dtype: float64

In [15]:
print('Количестов входных обучающих данных', len(x_train))
print('Количестов проверочных обучающих данных', len(y_train))
print('Количестов входных тестовых данных', len(x_test))
print('Количестов проверочных тестовых данных', len(y_test))

Количестов входных обучающих данных 442
Количестов проверочных обучающих данных 442
Количестов входных тестовых данных 111
Количестов проверочных тестовых данных 111

Вывод: В ходе данной практической работы, были преобрахованы признаки и разбит датасет на обучающую и тестовую выборку.